# Generated by Django 2.2.5 on 2021-02-24 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='viewfinder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL),
        ),
    ]
