# Generated by Django 2.2.5 on 2021-02-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210225_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='place_photos'),
        ),
    ]
