# Generated by Django 2.2.5 on 2021-03-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210225_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('jpy', 'JPY'), ('usd', 'USD'), ('krw', 'KRW')], default='jpy', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ja', 'Japanese'), ('en', 'English'), ('ko', 'Korean')], default='ja', max_length=2),
        ),
    ]
