# Generated by Django 2.2.5 on 2021-09-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210314_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('jpy', 'JPY'), ('usd', 'USD'), ('krw', 'KRW')], default='jpy', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ja', 'Japanese'), ('en', 'English'), ('ko', 'Korean')], default='ja', max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('kakao', 'Kakao'), ('line', 'Line')], default='email', max_length=50, verbose_name='login_method'),
        ),
        migrations.AlterField(
            model_name='user',
            name='supercontentprovider',
            field=models.BooleanField(default=False, verbose_name='supercontentprovider'),
        ),
    ]
