version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    restart: always
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - django_container_gunicorn

  django_container_gunicorn:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.prod
    networks:
      - network

networks:
  network:
