version: "3"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django_container_gunicorn:
    image: django_image:1
    env_file:
      - ./.env.prod
    networks:
      - network

networks:
  network:
